#!/usr/bin/env bash
# install nginx and configure server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
REDIRECT="https://www.youtube.com/watch?v=QH2-TGUlwu4"
FILE="/etc/nginx/sites-available/default"
sed -i "42a rewrite ^/redirect_me ""${REDIRECT}"" permanent;\n" $FILE
cd /etc/nginx/sites-available
sudo service nginx restart
