#!/usr/bin/env bash
# Add custom nginx response header and track which serveranswers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
REDIRECT="https://www.youtube.com/watch?v=QH2-TGUlwu4"
FILE="/etc/nginx/sites-available/default"
sudo sed -i "42a rewrite ^/redirect_me ""${REDIRECT}"" permanent;\n" $FILE
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "44a error_page 404 /custom_404.html; location = /custom_404.html { root /var/www/html/;internal;}" $FILE
sudo sed -i '37a add_header X-Served-By '"$HOSTNAME"';' $FILE
sudo service nginx restart
