#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
TIMESTAMP="$(date + "%d-%m-%Y")"
mysqldump -u root -p "$1" --all-databases > backup.sql
tar -czf "$TIMESTAMP.tar.gz" backup.sql
