#!/usr/bin/env bash
# my very own fizzbuzz shell loop
for (( i=1; i < 101; i++ ))
do
	if (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 && i % 3 == 0 ))
	then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
done
