#!/usr/bin/env bash
# advanced process and pid file
touch /var/run/holbertonscript.pid
pgrep -f "100-process_and_pid_file" > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
while true
do
	echo "To infinity and beyond"
done
