#!/usr/bin/env bash
# case example to print superstitious numbers
c=1
max=21
while [ "$c" -lt "$max" ]
do
	echo "$c"
	case "$c" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	(( c++ ))
done
