#!/usr/bin/env bash
# script to return file information
file=/home/vagrant/holberton-system_engineering-devops/0x04-loops_conditions_and_parsing/holbertonschool
if [ -e "$file" ]
then
	echo "holbertonschool file exists"
	if [ ! -s "$file" ]
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if [ -f "$file" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
