#!/usr/bin/env bash
# Script to repeat task but 7 or less lines
chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/' "$FILE"
sudo sed -i 's/80/8080/' "$FILE2"
pkill apache2
su nginx service nginx restart
